[libraries]
javalin-core = { group = "io.javalin", name = "javalin", version.ref="javalin" }
javalin-oapi-annotation-processor = { group = "io.javalin.community.openapi", name = "openapi-annotation-processor", version.ref="javalin-oapi" }
javalin-oapi-plugin = { group = "io.javalin.community.openapi", name = "javalin-openapi-plugin", version.ref="javalin-oapi" }
javalin-oapi-swagger = { group = "io.javalin.community.openapi", name = "javalin-swagger-plugin", version.ref="javalin-oapi" }
slf4j = { group = "org.slf4j", name = "slf4j-simple", version = "2.0.9" }

[versions]
javalin = "5.6.3"
javalin-oapi = "5.6.3-2"